- name: phd-assess secrets
  openshift:
    apiVersion: v1
    kind: Secret
    metadata:
      name: "{{ secret_name }}"
      namespace: "{{ openshift_namespace }}"
    type: Opaque
    data: >-
      {{ _data | from_yaml }}
  vars:
    _data: |
      "{{ encryption_key_name }}": "{{ lookup('file', '/keybase/team/epfl_phdassess/PHDASSESS_ENCRYPTION_KEY') | b64encode }}"

- name: phd-assess isa secrets
  openshift:
    apiVersion: v1
    kind: Secret
    metadata:
      name: "{{ isa_secret_name }}"
      namespace: "{{ openshift_namespace }}"
    type: Opaque
    data: >-
      {{ _data | from_yaml }}
  vars:
    _data: |
      "{{ isa_full_url_key_name }}": "{{ lookup('file', isa_url_keybase_path) | b64encode }}"
