# Production inventory
# N.B.: groups and group variables are defined in ../inventory.yml

all:
  children:
    openshift_namespaces:
      hosts:
        phd-assess:
          isa_url_keybase_path: "/keybase/team/epfl_phdassess/ISA_POST_STUDENT_RESULT_URL"
